#
# --------------------------------------------------------------------
# This script generates latex macros with the average, and maximum
# runtime (in seconds) of MBFL technique.
#
# Usage:
# Rscript mbfl_runtime.R <out_dir>
#
#  <out_dir>    Directory to which this script creates a file called
#               'macros_mbfl_runtime.tex' with the average, and
#               maximum runtime (in seconds) of MBFL technique.
#
# --------------------------------------------------------------------

##
#
##
print_macro <- function(name, value) {
  cat("\\def\\", name, "{", value, "\\xspace}\n", sep="")
}

# --------------------------------------------------------------- Main

# Read the output directory
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) {
  stop("Usage: Rscript mbfl_runtime.R <out_dir>")
}
out_dir <- args[1]

macros_file <- paste(out_dir, "/macros_mbfl_runtime.tex", sep="")
unlink(macros_file)
sink(macros_file, append=FALSE, split=TRUE)

cat("% These macros were generated by FL_DATA_HOME/stats/mbfl_runtime.R script at ", format(Sys.time(), "%a %b %d %X %Y"), "\n", sep="")

total_number_of_faults <- 4167 # TODO any chance we can get this number from any other script?!
total_runtime_hours <- "200000" # (this is estimation)
total_runtime_seconds <- strtoi(total_runtime_hours) * 60 * 60
total_runtime_days <- round(total_runtime_seconds / 86400)
total_runtime_weeks <- round(total_runtime_seconds / 604800)
total_runtime_months <- round(total_runtime_days / 30)
total_runtime_years <- round(total_runtime_days / 365.2425)

# there were at least 4 killmaps running for about 14 weeks
max_runtime_weeks <- 14
max_runtime_seconds <- round(max_runtime_weeks * 604800)
max_runtime_hours <- round(max_runtime_seconds / 60 / 60)
max_runtime_days <- round(max_runtime_seconds / 86400)

print_macro("meanMBFLRuntime", paste(round(strtoi(total_runtime_hours) / total_number_of_faults), " hours", sep=""))
print_macro("maxHoursMBFLRuntime", paste(max_runtime_hours, " hours", sep=""))
print_macro("maxDaysMBFLRuntime", paste(max_runtime_days, " days", sep=""))
print_macro("maxWeeksMBFLRuntime", paste(max_runtime_weeks, " weeks", sep=""))
print_macro("totalHoursMBFLRuntime", paste(total_runtime_hours, " hours", sep=""))
print_macro("totalDaysMBFLRuntime", paste(total_runtime_days, " days", sep=""))
print_macro("totalWeeksMBFLRuntime", paste(total_runtime_weeks, " weeks", sep=""))
print_macro("totalMonthsMBFLRuntime", paste(total_runtime_months, " months", sep=""))
print_macro("totalYearsMBFLRuntime", paste(total_runtime_years, " years", sep=""))

sink()

# EOF

