#
# --------------------------------------------------------------------
# This script generates latex macros with the average, median, maximum,
# and minimum runtime (in seconds) of SBFL technique.
#
# Usage:
# Rscript sbfl_runtime.R <data_file> <out_dir>
#
#  <data file>  Data file with runtime information for each D4J's
#               fault (one per row). File format should be:
#               project,fault,runtime(in seconds)
#
#  <out_dir>    Directory to which this script creates a file called
#               'macros_sbfl_runtime.tex' with the average, median,
#               maximum, and minimum runtime (in seconds) of SBFL
#               technique.
#
# --------------------------------------------------------------------

##
#
##
print_macro <- function(name, value) {
  cat("\\def\\", name, "{", value, "\\xspace}\n", sep="")
}

get_time_value <- function(time, key) {
  value <- as.integer(format(as.POSIXct('0001-01-01 00:00:00') + time, key))
  if (key == "%Y" || key == "%m" || key == "%j") {
    # -1, as it has been added 1 by the '0001-01-01 00:00:00'
    value <- value - 1
  }
  return(value)
}

##
#
##
format_time <- function(time_in_seconds) {
  y  <- get_time_value(time_in_seconds, "%Y")
  mo <- get_time_value(time_in_seconds, "%m")
  w  <- get_time_value(time_in_seconds, "%U")
  d  <- get_time_value(time_in_seconds, "%j")
  h  <- get_time_value(time_in_seconds, "%H")
  mi <- get_time_value(time_in_seconds, "%M")
  s  <- get_time_value(time_in_seconds, "%S")

  if (y == 0) {
    if (mo == 0) {
      if (w == 0) {
        if (d == 0) {
          if (h == 0) {
            if (mi == 0) {
              return(paste(s, " seconds", sep=""))
            } else {
              if (s > 0 && s < 60) { mi <- mi + 1 }
              return(paste(mi, " minutes", sep=""))
            }
          } else {
            if (mi > 0 && mi < 60) { h <- h + 1 }
            return(paste(h, " hours", sep=""))
          }
        } else {
          if (h > 0 && h < 24) { d <- d + 1 }
          return(paste(d, " days", sep=""))
        }
      } else {
        if (d > 0 && d < 366) { w <- w + 1 }
        return(paste(w, " weeks", sep=""))
      }
    } else {
      if (w > 0 && w < 53) { mo <- mo + 1 }
      return(paste(mo, " months", sep=""))
    }
  } else {
    if (mo > 0 && mo < 12) { y <- y + 1 }
    return(paste(y, " years", sep=""))
  }
}

# --------------------------------------------------------------- Main

# Read file name of the data file and the output directory
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2) {
  stop("Usage: Rscript sbfl_runtime.R <data_file> <out_dir>")
}
data_file <- args[1]
out_dir <- args[2]

df <- read.csv(data_file, header=T, stringsAsFactors=F)

macros_file <- paste(out_dir, "/macros_sbfl_runtime.tex", sep="")
unlink(macros_file)
sink(macros_file, append=FALSE, split=TRUE)

cat("% These macros were generated by FL_DATA_HOME/stats/sbfl_runtime.R script at ", format(Sys.time(), "%a %b %d %X %Y"), "\n", sep="")

##
# All faults

cat("% All faults\n", sep="")
print_macro("meanSBFLRuntime", format_time(mean(df$"runtime")))
print_macro("medianSBFLRuntime", format_time(median(df$"runtime")))
print_macro("maxSBFLRuntime", format_time(max(df$"runtime")))
print_macro("minSBFLRuntime", format_time(min(df$"runtime")))
print_macro("totalSBFLRuntime", format_time(sum(df$"runtime")))

print_macro("numFaultsUnderMeanSBFLRuntime", nrow(df[df$"runtime" <= mean(df$"runtime"), ]))
print_macro("numFaultsUnderMedianSBFLRuntime", nrow(df[df$"runtime" <= median(df$"runtime"), ]))

print_macro("percentageFaultsUnderMeanSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[df$"runtime" <= mean(df$"runtime"), ]) / nrow(df) * 100, digits=1)), "\\%", sep=""))
print_macro("percentageFaultsUnderMedianSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[df$"runtime" <= median(df$"runtime"), ]) / nrow(df) * 100, digits=1)), "\\%", sep=""))

##
# Only real faults

mask_real <- df$"fault" < 1000

cat("% Only real faults\n", sep="")
print_macro("meanSBFLRuntimeRealFaults", format_time(mean(df$"runtime"[mask_real])))
print_macro("medianSBFLRuntimeRealFaults", format_time(median(df$"runtime"[mask_real])))
print_macro("maxSBFLRuntimeRealFaults", format_time(max(df$"runtime"[mask_real])))
print_macro("minSBFLRuntimeRealFaults", format_time(min(df$"runtime"[mask_real])))
print_macro("totalSBFLRuntimeRealFaults", format_time(sum(df$"runtime"[mask_real])))

print_macro("numRealFaultsUnderMeanSBFLRuntime", nrow(df[mask_real & df$"runtime" <= mean(df$"runtime"[mask_real]), ]))
print_macro("numRealFaultsUnderMedianSBFLRuntime", nrow(df[mask_real & df$"runtime" <= median(df$"runtime"[mask_real]), ]))

print_macro("percentageRealFaultsUnderMeanSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[mask_real & df$"runtime" <= mean(df$"runtime"[mask_real]), ]) / nrow(df[mask_real, ]) * 100, digits=1)), "\\%", sep=""))
print_macro("percentageRealFaultsUnderMedianSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[mask_real & df$"runtime" <= median(df$"runtime"[mask_real]), ]) / nrow(df[mask_real, ]) * 100, digits=1)), "\\%", sep=""))

##
# Only artificial faults

mask_artificial <- df$"fault" > 1000

cat("% Only artificial faults\n", sep="")
print_macro("meanSBFLRuntimeArtificialFaults", format_time(mean(df$"runtime"[mask_artificial])))
print_macro("medianSBFLRuntimeArtificialFaults", format_time(median(df$"runtime"[mask_artificial])))
print_macro("maxSBFLRuntimeArtificialFaults", format_time(max(df$"runtime"[mask_artificial])))
print_macro("minSBFLRuntimeArtificialFaults", format_time(min(df$"runtime"[mask_artificial])))
print_macro("totalSBFLRuntimeArtificialFaults", format_time(sum(df$"runtime"[mask_artificial])))

print_macro("numArtificialFaultsUnderMeanSBFLRuntime", nrow(df[mask_artificial & df$"runtime" <= mean(df$"runtime"[mask_artificial]), ]))
print_macro("numArtificialFaultsUnderMedianSBFLRuntime", nrow(df[mask_artificial & df$"runtime" <= median(df$"runtime"[mask_artificial]), ]))

print_macro("percentageArtificialFaultsUnderMeanSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[mask_artificial & df$"runtime" <= mean(df$"runtime"[mask_artificial]), ]) / nrow(df[mask_artificial, ]) * 100, digits=1)), "\\%", sep=""))
print_macro("percentageArtificialFaultsUnderMedianSBFLRuntime", paste(sprintf("%.1f", round(nrow(df[mask_artificial & df$"runtime" <= median(df$"runtime"[mask_artificial]), ]) / nrow(df[mask_artificial, ]) * 100, digits=1)), "\\%", sep=""))

sink()

# EOF

